### check valid user - 201
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/vnd.api+json

{
  "firstName": "Test",
  "lastName": "Testovich",
  "email": "test3@test.test",
  "passwordHash": "123456",
  "birthday": "2020-01-01",
  "gender": "male"
}

### check invalid user name - 422
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/vnd.api+json

{
  "firstName": "test",
  "lastName": "testovich",
  "email": "testtest.test",
  "passwordHash": "123456",
  "birthday": "2020-01-01",
  "gender": "male"
}
### check another invalid user ... - 422

### check invalid user email constraint unique - 422
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/vnd.api+json

{
  "firstName": "Test",
  "lastName": "Testovich",
  "email": "test@test.test",
  "passwordHash": "123456",
  "birthday": "2020-01-01",
  "gender": "male"
}